//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

pub mod prelude;

pub mod document;
pub mod document_version;
pub mod embedding;
pub mod project;
pub mod project_version;
pub mod role_permission;
pub mod sea_orm_active_enums;
pub mod user_permission;
