//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

pub use super::document::Entity as Document;
pub use super::document_version::Entity as DocumentVersion;
pub use super::project::Entity as Project;
pub use super::project_version::Entity as ProjectVersion;
pub use super::role_permission::Entity as RolePermission;
pub use super::user_permission::Entity as UserPermission;
